version: "3"
services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
  portcast:
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db